source 'https://rubygems.org'

gem 'adhearsion', '= 2.6.2'
gem 'adhearsion-i18n'
gem 'matrioska'

group :asterisk do
  gem 'adhearsion-asterisk'
end

group :web, :api do
  gem 'virginia'
  gem 'sinatra', require: false
end

group :development, :test do
  gem 'rspec'
  gem 'rspec-expectations'
end

