source 'https://rubygems.org'

group :alpine_linux do
  gem 'ffi', '= 1.9.14'
end

gem 'adhearsion', '= 2.6.3'
gem 'matrioska'

group :asterisk do
  gem 'adhearsion-asterisk'
end

group :web, :api do
  gem 'sinatra', require: false
end

group :development, :test do
  gem 'rspec'
  gem 'rspec-expectations'
end

